<?php

/**
 * @file
 * Contains dru_chat.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dru_chat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dru_chat module.
    case 'help.page.dru_chat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Live, realtime chat for drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function dru_chat_install($is_syncing) {
  #$server = Drupal::service('dru_chat.server');
  #$server->startSocketServer();
  // TODO:: remove later
}

/**
 * Implements hook_theme().
 */
function dru_chat_theme() {
  return [
    'dru_chat_block' => [
      'variables' => [
        'data' => NULL
      ],
      'render element' => 'children',
      'template' => 'dru-chat-block',
    ],

    'dru_chat_messages' => [
      'variables' => [
        'data' => NULL
      ],
      #'render element' => 'children',
      'template' => 'dru-chat-messages',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function dru_chat_page_attachments(array &$attachments){

  $current_user = Drupal::currentUser()->id();

  $attachments['#attached']['drupalSettings']['dru_chat']['user'] = $current_user;

}